language: ruby
rvm: 2.2

before_install:
  gem install awesome_bot  

before_script:
  git clone --depth=1 https://github.com/Kickball/awesome-selfhosted.git
  
script:
  - node awesome-selfhosted/test.js awesome-selfhosted/README.md
  - awesome_bot -f awesome-selfhosted/README.md,awesome-selfhosted/non-free.md --allow-ssl --allow-dupe --allow-redirect --allow 403,429 || (exit 0)
  - mkdir out
  - grep -Pos "####\s.*(?=\")" ab-results-awesome-selfhosted-non-free.md-markdown-table.json | awk '{gsub(/\\n/,"\n")}1' | sed 's/\([[:digit:]]\+[[:space:]]|\)/ \<ul\>\<li\> [x] \<\/li\>\<\/ul\> | \1/g' > out/non-free_results.md
  - grep -Pos "####\s.*(?=\")" ab-results-awesome-selfhosted-README.md-markdown-table.json | awk '{gsub(/\\n/,"\n")}1' | sed 's/\([[:digit:]]\+[[:space:]]|\)/ \<ul\>\<li\> [x] \<\/li\>\<\/ul\> | \1/g' > out/free_results.md
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  target_branch: results-$(date +%Y%m%d-%H%M)
  on:
    branch: master
    
notifications:
  email: false
